version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: test-db2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data2:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    environment:
      PORT: 8000
      POSTGRES_DB: test-db2
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres-data2:
