networks:
  weightlifting-app-network:
    external: true

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - weightlifting-app-network

  app:
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile-app
    environment:
      PORT: 8000
      POSTGRES_DB: postgres-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    ports:
      - "80:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - weightlifting-app-network

volumes:
  postgres-data:
  redis-data:
