version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: noname
      POSTGRES_PASSWORD: noname
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    image: ghcr.io/maratumerow/weightlifting-app:latest
    environment:
      PORT: 8000
      DATABASE_URL: postgres://noname:noname@db:5432/postgres
    ports:
      - "80:8000"
    depends_on:
      - db

volumes:
  postgres-data:
