"""added field is_test in users 

Revision ID: aad700cbe4c3
Revises: a14527cf38c3
Create Date: 2024-07-29 21:47:36.227563

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aad700cbe4c3"
down_revision: Union[str, None] = "a14527cf38c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("is_test", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "is_test")
    # ### end Alembic commands ###
