"""Initial migration

Revision ID: 32fde7487321
Revises: aad700cbe4c3
Create Date: 2024-08-28 13:16:20.211351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32fde7487321'
down_revision: Union[str, None] = 'aad700cbe4c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_test')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_test', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
